server:
  port: 8000

#自定义socketio配置
socketio:
  # socketIO请求地址
  host: 192.168.0.23
  # socketIO端口
  port: 9000
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  # 连接数大小
  workCount: 100
  # 允许客户请求
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 60000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000
  # 命名空间，多个以逗号分隔，
  namespaces: /user
  #业务大群房间ID
  defaultRoomId: 2023

# 定时任务
schedule:
  # 心跳
  heartbeat:
    # 频率s
    delay: 10
    # 批量数量
    batchSize: 100

theadPool:
  corePoolSize: 8
  maximumPoolSize: 100
  keepAliveTime: 60
  capacity: 50
